### ISSUE TITLE
Decrease RAM usage of Import Sample Dialog

### ISSUE THREAD

**Issue by maks** [democloid/picoTracker#14]
Currently its not possible to open a directory containing more than about 25 samples because of the large amounts of ram used by the Import Sample dialog that came from LGPT.

This occurs for several reasons:
1. `I_Dir` is just a subclass of `T_SimpleList<Path>` so that everyfile in a directory is actually stored in the list with its full path not just the filename, so the containing directories path is stored in every files `Path` object
1. The whole contents of a directory are read into the `I_Dir` list when entering the directory, even though only 15 (`LIST_SIZE`) can be displayed at any one time by the UI, but this is necessary in order to be able to sort the file list for a dir
1. The `ImportSampleDialog` itself maintains another list `sampleList_` that it then copies (based on filter criteria, eg, if dir, if `*.wav`, the items from the list returned in the `I_Dir` object by `picoTrackerFileSystem`.

In my initial testing, it seems there is only a few (3-5?) KB of ram available for the ImportSampleDialog to use so the above code is very limiting in what size of dirs can be handled at the moment.

To try to improve this my plan is to create a new `PagedImportSampleDialog` class that uses paging, so that it only ever requests the 15 items it needs to display at any time. Then I need to create a new interface, `I_PagedDir` that supports being given a dir path and a s start index and it returns the 15 items from that start index. 

**But** the tricky thing here is: sorting. In order to be able to sort a directory, the new `I_PagedDir` would need to read and store every filename in a dir and that could just be itself run out of ram in large dirs: eg. for a dir with 300 files, average filename length of 20 chars gives: ~5.9KB and blows the ram budget. SDFat is capable of dealing with files just by a "directory index" `int` BUT then there is no way to alphabetically sort the contents :-(

So the 2 options I can see for the above are:

a. allow upto thousands of files per dir BUT they will not be sorted when displayed (except for subdirs which could at least be sorted to be at the start of the list)

b. limit the number of files based on filename lengths this could be anywhere from 20 to 100 but still allow for displaying them in alpha sorted order.

**Comment by democloid** [comment]
Couldn't we just do a much slower but potentially fast enough approach? Thinking if we could build a list of directory indices and sort it by reading from SD each time we need to.
Another advantage of this approach is that we could use static memory for this list, say we want to support 100 files per directory, then we use a static 400 bytes (indices are uint32) for storing and sorting files in each view. Even wonder if we could cast indices to a smaller int in practice.

Otherwise I'd just go with no sorting probably.

Option b is not something we want to do. While there is a lot of dynamic memory being used in picoTracker, any new features should be developed with a fixed memory footprint in mind. Otherwise it's really hard to add/remove features without breaking things.
