### ISSUE TITLE
Improve UX of the the Sample Import Dialog 

### ISSUE THREAD

**Issue by maks** [democloid/picoTracker#31]
Currently the Sample Import Dialog UI is inherited from lgpt and uses onscreen buttons which don't really make sense for a UX that is directed at ergonomic use of the hardware keys. Therefore it would be nice to improve the UX by replacing the functionality of the buttons with just direct mapping of those functions to the physical keys.

**Comment by democloid** [comment]
@maks I'm not entirely sure about the UI on this one TBH. Is this replicating M8 or is original workflow?

Couple of thoughts to start a discussion:
I feel it's unintuitive that we enter with A, but exit with shift+left. Should these be power user shortcuts while maintaining the old UI buttons?

Plus it seems we are breaking the consistency in terms of pop-up windows having navigation buttons vs shift+arrows for normal page navigation.

Should the dialog be a screen instead? this has it's own intuitiveness problems IMO, but I could see a path where everything is a screen unless it's a "yes/no" or "ok" kind of dialog like in the load/save or firmware update dialogs.

**Comment by maks** [comment]
Thanks @democloid all very good points! 👍🏻 

I must admit I don't really remember much of using the M8 when I had a headless setup, so this was mostly my own "UX design"  plus based on comments I saw from one user on discord mentioning just using physical keys instead of onscreen button widgets.

I did just go look at a video of a M8 being used and at the manual and looks like its file browser doesn't use any onscreen buttons and it uses the "Option" button to exit the file browser (M8 manual doesn't call it a "dialog"). It also uses the "Play" button to preview samples and the "Edit" button to load.

I think it would make sense to match the M8's UX for the sake of existing users as theres no preexisting ones in lgpt anyways.

For me, I think its better that this (and the project browser) stay a "dialog" or "popup window" and not another "screen" though could really stop calling it that and also get rid of the not very useful colour border drawn around it. But also you've highlighted a good  point that really need to make the project browser consistent and use the same ui & code.

So @democloid in summary, what do you think about:
* keep file browser as a "popup aka dialog" but remove border
* use above key functions (same as M8)
* make project browser use same UI
?

**Comment by maks** [comment]
I should also add that even in my brief testing, the current onscreen buttons I found quite annoying, as my usual pattern of using the sample browser is: quickly scroll through samples, playing one after another in rapid succession, when I hear one I like, import it and then keep scrolling through looking for more and then import next one I like. Doing the above with onscreen keys I found very error prone, as I'd keep forgetting to move the selected button from [Import] back to [Listen] and then keep importing samples I didnt mean to.

**Comment by democloid** [comment]
@maks 
Couple of thoughts:
1. Again, not sure how it works in M8, but I feel having different button to browse vs "play" is kinda weird. I naturally gravitate towards trying to use the same button for up/down dirs and "play" the sample (in my case that's A, but that's less important)
2. In terms of rapid browsing (with which I agree with you), I feel it's better if playing a sample stops previous playback and starts new rather than having to stop first. Disadvantage with this is that there would be no stop button with this way. Ideal would probably be: If play is pressed again in same sample, then it stops. If play is pressed again in new sample, start that new sample (while first stopping playback of previous, if still playing)
3. Don't personally care that much about border or not, maybe it's not bad in terms of hinting the user that it's a different type of screen
4. Project window is separate IMO. Do you propose removing Load/New there too?

As an additional thing we could think about here, even if not implemented right away, how do you effectively listen to single cycle samples? Maybe UX could be that maintaining "play" pressed will play continuously and loop around.

**Comment by maks** [comment]
1. Yes I chose using the Play button just because of the association of it being "play"  and it was easier not needing to add check in button action handler for if selected item was file or subdir 🙂  but totally fine with using `A` instead if you prefer that?
2. Yes sure thing, can implement it that way, so that starting play on a sample while another one is playing, stops it first, would you like me to implement it that way?
3. Ah good point, it is a good way to show that, I just make it a bit thinner and then we could fit a few more chars per line though that eats into ram a bit more, I've noticed some people like long filenames for samples 😅  
4. Yes project is separate but I'd like to make it consistent with this UI. And yes I was wanting to remove the buttons there too and instead have load/new in the project screen. That is influenced by how M8 has it, but now that I've seen its design I like it and cant un-see it 🙂 If you are ok with doing that, I'll make a separate issue to track work on changing the project file browser too. 
 
If we agree on above, at this point I think I would also remove the original ImportDialog code and just have some `ifdef`s just to set picotracker specifics like size of the file item vectors.

And funny you mention single cycle previews as I was thinking about that too just yesterday as I was trying to use some and it was annoying not to be able to audition them. I'll raise an new issue for that as I had some initial thoughts on how to handle that.

**Comment by democloid** [comment]
@maks let's roll with this
