### ISSUE TITLE
Mirror image on the display

### ISSUE THREAD

**Issue by go-0dboy** [democloid/picoTracker#51]
When the ST7735 (https://aliexpress.ru/item/4001282467099.html?sku_id=12000027429251038) display is connected, the image is displayed in a mirror image.

**Comment by democloid** [comment]
The official screen used is a ILI9341. I know they are normally listed together, but I'm not sure if they are supposed to be 100% compatible.
I don't have one of these screens right now to test this on, but will probably buy one to test. Don't know if there would be a way to easily detect what screen is connected in order to know orientation.

If you're able to compile your own firmware I can give you some pointers about where you can rotate the screen.

**Comment by go-0dboy** [comment]
Thanks for the reply. 
Unfortunately, I do not know how to determine the type of display. 
But I was able to put the project together. 
Can you tell me what changes need to be made?

**Comment by democloid** [comment]
You can change this line and pass the value 0x48 to flip the screen vertically:
https://github.com/democloid/picoTracker/blob/master/sources/Adapters/picoTracker/display/ili9341.c#L96

Let me know how it goes!

**Comment by go-0dboy** [comment]
Thanks, it worked out. 
The correct value 0xCC.

ILI9341_MADCTL_MY|ILI9341_MADCTL_MX|ILI9341_MADCTL_MH|ILI9341_MADCTL_BGR; //180 degree

**Comment by maks** [comment]
Thats good news, thanks for reporting back with that @go-0dboy . 
I guess the next step would be to add this as maybe a `#define` to allow builds with this screen versus the existing one.
